version: "3.9"

services:
  excubya:
    build: .
    container_name: excubya
    ports:
      - "8000:8000"
    volumes:
      - ./snapshots:/app/snapshots
      - ./recordings:/app/recordings
      - ./logs:/app/logs
      - ./models:/app/models
      - ./excubya.db:/app/excubya.db
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - EXCUBYA_HOST=0.0.0.0
      - EXCUBYA_PORT=8000
